matrix:
  platform:
    - linux/amd64
    - linux/arm64

labels:
  type: exec
  platform: ${platform}

steps:
- name: publish-linux
  image: bash
  commands:
  - export REGISTRY=$DRYCC_REGISTRY/drycc-addons
  - export IMAGE_NAME=$CI_REPO_NAME
  - export TAG=$([ -z $CI_COMMIT_TAG ] && echo latest || echo $CI_COMMIT_TAG)
  - export OUTPUT_TYPE=docker
  - echo $CONTAINER_PASSWORD | docker login $DRYCC_REGISTRY --username $CONTAINER_USERNAME --password-stdin > /dev/null 2>&1
  - export ARCH=$(sed 's#linux/##g' <<< $CI_SYSTEM_PLATFORM)
  - make image
  - docker push $REGISTRY/$IMAGE_NAME:$TAG-linux-$ARCH-amazon
  environment:
    CODENAME:
      from_secret: codename
    DEV_REGISTRY:
      from_secret: dev_registry
    DRYCC_REGISTRY:
      from_secret: drycc_registry
    CONTAINER_USERNAME:
      from_secret: container_username
    CONTAINER_PASSWORD:
      from_secret: container_password
  when:
    event:
    - push
    - tag
